#!/usr/bin/env python3
"""
Croton Packing List Processor  (v2 — Hoja1_2 format)
======================================================
Input : ODS packing-list  — two sheets:
          * Hoja1    = raw packing list (CODIGO interno)
          * Hoja1_2  = enriched sheet generated by operators (PARTIDA / referencia)
                       ← THIS is the sheet we read
        FACTURA XLSX  — invoice with commercial values per REFERENCIA

Output: ODS with an extra 'Resumen_Partidas' sheet (injected into source ODS)
        or standalone ODS (write_output mode).

Why no product_mapping needed:
  Hoja1_2 col3 already contains the REFERENCIA/PARTIDA that operators assigned.
  That same REFERENCIA is col0 in the FACTURA → direct join, no CSV mapping.

Pipeline:
  Hoja1_2  →  extract summary rows (one per product group)
           →  enrich VALOR proportionally from FACTURA XLSX
           →  aggregate by (MERCANCIA, PARTIDA)  →  Resumen_Partidas ODS sheet

Hoja1_2 column layout (0-based):
  0  = LINEA
  1  = Nº BULTO
  2  = DESCRIPCION   <- MERCANCIA
  3  = PARTIDA       <- REFERENCIA / codigo arancelario
  4  = NºPALET
  5  = PESO NETO kg/bulto
  6  = PESO BRUTO kg/bulto
  7  = CANT. del bulto
  8  = CANT. TOTAL MT/UD  <- non-empty -> summary row for the group
  9  = m2 total del grupo
  10 = gramos (gramaje)
  11 = neto total del grupo (kg)
  12 = bruto total del grupo (kg)
  13 = bultos (nº bultos del grupo)
  14 = valor € (may be empty -> computed from FACTURA)

Summary rows are identified by col8 having a numeric value
(not empty and not "#¡DIV/0!").  Individual bulto rows are ignored.
"""

import os
import sys
import csv
import shutil
import logging
import argparse
import zipfile
from collections import OrderedDict, defaultdict
from pathlib import Path
from xml.etree import ElementTree as ET
from typing import Optional

EXTRACTOR_DIR = Path(__file__).parent
MAPPING_FILE  = EXTRACTOR_DIR / "product_mapping.csv"

import openpyxl
from odf.opendocument import load, OpenDocumentSpreadsheet
from odf.table import Table, TableRow, TableCell
from odf.text import P
from odf.style import Style, TextProperties, TableCellProperties

# ─────────────────────────────────────────────────────────────────────────────
# Logging
# ─────────────────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers – parse numbers
# ─────────────────────────────────────────────────────────────────────────────

def _parse_num(value: str) -> Optional[float]:
    """
    Parse number string to float. Handles both notations:
      - Spanish/EU: dot = thousands sep, comma = decimal  (e.g. '1.234,56' → 1234.56)
      - English/ODS: dot = decimal                         (e.g. '1234.56' → 1234.56)

    Disambiguation rule:
      - If the string contains a comma → Spanish format → strip dots, replace comma with dot
      - If the string contains a dot but no comma → English format → use as-is
      - Otherwise → integer
    """
    if not value or value.strip() in ('#\xa1DIV/0!', '#DIV/0!', '#N/A', '#REF!', ''):
        return None
    clean = value.strip().replace('\xa0', '')
    if not clean:
        return None
    if ',' in clean:
        # Spanish format: '1.234,56' or '1,60'
        clean = clean.replace('.', '').replace(',', '.')
    # else: English/plain format — use as-is (dots are decimal points)
    try:
        return float(clean)
    except ValueError:
        return None


def _fmt(value: float) -> str:
    """Format float to Spanish-style string (comma decimal, no trailing zeros)."""
    if value == 0:
        return ""
    s = f"{value:.4f}".rstrip("0").rstrip(".")
    return s.replace(".", ",")


# ─────────────────────────────────────────────────────────────────────────────
# Step 1 – read Hoja1_2 from ODS
# ─────────────────────────────────────────────────────────────────────────────

def _ods_sheet_names(path: str) -> list:
    """Return all sheet names in the ODS file."""
    with zipfile.ZipFile(path) as z:
        with z.open('content.xml') as f:
            tree = ET.parse(f)
    ns = {'table': 'urn:oasis:names:tc:opendocument:xmlns:table:1.0'}
    return [
        s.get('{urn:oasis:names:tc:opendocument:xmlns:table:1.0}name')
        for s in tree.getroot().findall('.//table:table', ns)
    ]


def _read_ods_sheet(path: str, sheet_name: str) -> list:
    """Read one ODS sheet into a list of row-lists (all values as strings)."""
    with zipfile.ZipFile(path) as z:
        with z.open('content.xml') as f:
            tree = ET.parse(f)
    root = tree.getroot()
    ns = {
        'table': 'urn:oasis:names:tc:opendocument:xmlns:table:1.0',
        'text':  'urn:oasis:names:tc:opendocument:xmlns:text:1.0',
    }
    for sheet in root.findall('.//table:table', ns):
        name = sheet.get('{urn:oasis:names:tc:opendocument:xmlns:table:1.0}name')
        if name != sheet_name:
            continue
        rows_out = []
        for row in sheet.findall('table:table-row', ns):
            vals = []
            for cell in row.findall('table:table-cell', ns):
                rep = cell.get(
                    '{urn:oasis:names:tc:opendocument:xmlns:table:1.0}'
                    'number-columns-repeated'
                )
                txt = ''.join(p.text or '' for p in cell.findall('.//text:p', ns))
                n = int(rep) if rep and int(rep) < 50 else 1
                vals.extend([txt] * n)
            rows_out.append(vals)
        return rows_out
    raise ValueError(f"Sheet '{sheet_name}' not found in {path}")


def _detect_enriched_sheet(path: str) -> str:
    """
    Auto-detect the enriched sheet (Hoja1_2 or equivalent).
    Priority:
      1. Any sheet whose name contains '1_2' or '1.2'
      2. Second sheet (index 1)
      3. First (and only) sheet
    """
    names = _ods_sheet_names(path)
    for n in names:
        if '1_2' in n or '1.2' in n:
            log.info("Using enriched sheet '%s' from %s.", n, path)
            return n
    if len(names) > 1:
        log.info("No '*1_2*' sheet found; using second sheet '%s'.", names[1])
        return names[1]
    log.warning("Only one sheet found; using '%s'.", names[0])
    return names[0]


def read_hoja1_2(ods_path: str) -> list:
    """
    Read Hoja1_2 (or equivalent enriched sheet) and return one dict per
    product group.

    Two ODS formats are supported, auto-detected from the sub-header row:

    FORMAT A — new format (MFMP-26 style, ref interna in col3):
      col2 = DESCRIPCION, col3 = ref_interna (RF004, RFCANALE…)
      col5 = NETO kg/bulto,  col6 = BRUTO kg/bulto
      col8 = CANT.TOTAL (summary row), col9 = m², col13 = bultos, col14 = valor

    FORMAT B — classic format (MFMP-25 manual style, arancelario already in col2):
      col0 = BULTO, col1 = MERCANCIA, col2 = PARTIDA arancelaria, col3 = ORDEN
      col4 = NETO kg/bulto, col5 = BRUTO kg/bulto
      col7 = CANT.TOTAL (summary row), col8 = m², col12 = bultos, col13 = valor

    In Format B the mapping step is skipped — MERCANCIA and PARTIDA are injected
    directly into the output dict.
    """
    sheet_name = _detect_enriched_sheet(ods_path)
    rows = _read_ods_sheet(ods_path, sheet_name)

    # Auto-detect format by inspecting sub-header row (row index 2 when present)
    # Format B sub-header has 'PARTIDA' in col2 and the first data rows have numeric col2
    fmt_b = False
    for r in rows[2:6]:
        if len(r) > 2 and r[2].strip().replace('.','').isdigit() and len(r[2].strip()) >= 8:
            fmt_b = True
            break

    if fmt_b:
        log.info("Detected FORMAT B (classic/manual style — arancelario already in col2).")
    else:
        log.info("Detected FORMAT A (new style — ref interna in col3).")

    result = []
    cur_neto  = 0.0
    cur_bruto = 0.0

    if fmt_b:
        # Format B: ONE ROW per product group (each row = complete group summary).
        # col0=BULTO(last), col1=MERCANCIA, col2=PARTIDA, col3=ORDEN
        # col4=NETO/last-bulto, col5=BRUTO/last-bulto  ← NOT the group total
        # col7=CANT.TOTAL, col8=m²
        # col10=NETO_group_total, col11=BRUTO_group_total  ← USE THESE
        # col12=BX (nº bultos), col13=VALOR
        for row in rows[3:]:   # skip 3 header rows
            while len(row) < 14:
                row.append('')
            bulto = row[0].strip()
            if not bulto.isdigit():
                continue
            mercancia = row[1].strip()
            partida   = row[2].strip()
            if not mercancia or not partida.replace('.','').isdigit():
                continue
            cant_total = _parse_num(row[7])
            if cant_total is None:
                continue
            result.append({
                'referencia':      partida,
                'descripcion':     mercancia,
                'mercancia':       mercancia,
                'partida_arancel': partida,
                'cant_total':      cant_total,
                'm2':              _parse_num(row[8])  or 0.0,
                'neto':            _parse_num(row[10]) or 0.0,
                'bruto':           _parse_num(row[11]) or 0.0,
                'bultos':          _parse_num(row[12]) or 0.0,
                'valor':           _parse_num(row[13]),
            })
    else:
        # Format A: col2=DESCRIPCION, col3=ref_interna
        # Each consecutive run of rows terminated by a summary row (col8 non-empty)
        # forms one product group.  Bultos = col13 of summary row when present,
        # otherwise count the number of rows in the group.
        row_count = 0
        for row in rows[1:]:
            while len(row) < 15:
                row.append('')
            ref  = row[3].strip()
            desc = row[2].strip()
            if not ref or not desc:
                continue
            row_count += 1
            cur_neto  += _parse_num(row[5]) or 0.0
            cur_bruto += _parse_num(row[6]) or 0.0
            cant_total = _parse_num(row[8])
            if cant_total is not None:
                bultos_col = _parse_num(row[13])
                result.append({
                    'referencia':  ref,
                    'descripcion': desc,
                    'cant_total':  cant_total,
                    'm2':          _parse_num(row[9])  or 0.0,
                    'neto':        round(cur_neto,  2),
                    'bruto':       round(cur_bruto, 2),
                    'bultos':      bultos_col if bultos_col is not None else float(row_count),
                    'valor':       _parse_num(row[14]),
                })
                cur_neto  = 0.0
                cur_bruto = 0.0
                row_count = 0

    log.info("Read %d groups from sheet '%s'.", len(result), sheet_name)
    return result


# ─────────────────────────────────────────────────────────────────────────────
# Step 2 – load product_mapping.csv and resolve MERCANCIA + PARTIDA arancelaria
# ─────────────────────────────────────────────────────────────────────────────

def load_mapping(csv_path: str) -> list:
    """
    Load product_mapping.csv and return list of rule dicts.
    Columns: CODIGO, DESCRIPCION_CONTAINS, MERCANCIA, PARTIDA
    """
    rules = []
    with open(csv_path, newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            codigo = row.get('CODIGO', '').strip()
            if not codigo or codigo.startswith('#'):
                continue
            rules.append({
                'codigo':    codigo.upper(),
                'contains':  row.get('DESCRIPCION_CONTAINS', '').strip().upper(),
                'mercancia': row.get('MERCANCIA', '').strip(),
                'partida':   row.get('PARTIDA', '').strip(),
            })
    log.info("Loaded %d mapping rules from %s.", len(rules), csv_path)
    return rules


def lookup(referencia: str, descripcion: str, rules: list):
    """
    Return (mercancia, partida) for a line.
    Match priority: exact CODIGO + DESCRIPCION_CONTAINS → exact CODIGO (no contains).
    Raises ValueError if not found.
    """
    ref_up  = referencia.strip().upper()
    desc_up = descripcion.strip().upper()
    # First pass: rules that have a DESCRIPCION_CONTAINS filter
    for rule in rules:
        if rule['codigo'] != ref_up:
            continue
        if rule['contains'] and rule['contains'] in desc_up:
            return rule['mercancia'], rule['partida']
    # Second pass: rules with no filter (catch-all for that CODIGO)
    for rule in rules:
        if rule['codigo'] != ref_up:
            continue
        if not rule['contains']:
            return rule['mercancia'], rule['partida']
    raise ValueError(
        f"No mapping for REFERENCIA='{referencia}' DESCRIPCION='{descripcion}'"
    )


def apply_mapping(lineas: list, rules: list) -> list:
    """
    Add 'mercancia' and 'partida_arancel' to each line using the mapping.
    Lines that cannot be resolved are dropped with a warning.
    """
    result = []
    errors = []
    for l in lineas:
        try:
            merc, part = lookup(l['referencia'], l['descripcion'], rules)
            l['mercancia']      = merc
            l['partida_arancel'] = part
            result.append(l)
        except ValueError as e:
            errors.append(str(e))
            log.warning(str(e))
    if errors:
        log.warning(
            "%d line(s) dropped — add to product_mapping.csv:\n  %s",
            len(errors), "\n  ".join(errors)
        )
    return result


# ─────────────────────────────────────────────────────────────────────────────
# Step 3 – load FACTURA XLSX and enrich VALOR
# ─────────────────────────────────────────────────────────────────────────────

def load_factura(xlsx_path: str) -> dict:
    """
    Load FACTURA XLSX and return per-REFERENCIA invoice data:
      REFERENCIA_UPPER -> { cant_total, importe_total }

    Column layout (sheet 'TOTAL FRA.' or first sheet):
      col A (0) = REFERENCIA
      col F (5) = CANTIDAD MTS / KGS
      col I (8) = IMPORTE EUR

    Multiple lines with the same REFERENCIA are summed (e.g. RF385 BLANCA +
    RF385 COLORES -> single entry).
    """
    wb = openpyxl.load_workbook(xlsx_path, data_only=True)
    ws = wb["TOTAL FRA."] if "TOTAL FRA." in wb.sheetnames else wb.active
    log.info("Reading FACTURA from sheet '%s' in %s.", ws.title, xlsx_path)

    _SKIP = {
        'referencia', 'importe', 'forma', 'total', 'transferencia',
        'domicilio', 'incoterm', 'ifortex', 'mendez', 'nif', 'lot',
        'tanger', 'marruecos', 'avda', 'tel', 'num.', 'num',
    }

    cant_map    = defaultdict(float)
    importe_map = defaultdict(float)

    for row in ws.iter_rows(values_only=True):
        ref_raw = row[0]
        if ref_raw is None:
            continue
        ref = str(ref_raw).strip()
        if not ref or ref.lower().split()[0] in _SKIP:
            continue
        try:
            cant    = float(row[5]) if row[5] is not None else None
            importe = float(row[8]) if row[8] is not None else None
        except (ValueError, TypeError):
            continue
        if cant is None or importe is None or importe < 1.0:
            continue
        cant_map[ref.upper()]    += cant
        importe_map[ref.upper()] += round(importe, 4)

    wb.close()

    result = {
        ref: {'cant_total': cant_map[ref], 'importe_total': importe_map[ref]}
        for ref in importe_map
    }
    log.info(
        "Loaded FACTURA: %d references, total %.2f EUR.",
        len(result), sum(v['importe_total'] for v in result.values())
    )
    return result


def enrich_valor_from_factura(lineas: list, factura: dict) -> list:
    """
    Fill in missing VALOR for each line using the FACTURA (proportional).

      valor_linea = (cant_linea / cant_total_factura_ref) * importe_factura_ref

    ODS valor takes priority: if valor is already set (not None) -> keep it.
    """
    for linea in lineas:
        if linea['valor'] is not None:
            linea['valor_fuente'] = 'ODS'
            continue

        ref = linea['referencia'].upper()
        if ref in factura:
            inv = factura[ref]
            if inv['cant_total'] and inv['cant_total'] > 0:
                proporcion = linea['cant_total'] / inv['cant_total']
                linea['valor'] = round(proporcion * inv['importe_total'], 2)
                linea['valor_fuente'] = 'FACTURA'
            else:
                linea['valor_fuente'] = 'SIN_DATOS'
        else:
            linea['valor_fuente'] = 'SIN_REF'
            log.warning(
                "REFERENCIA '%s' (%s) not found in FACTURA — VALOR left empty.",
                linea['referencia'], linea['descripcion'][:40]
            )

    return lineas


# ─────────────────────────────────────────────────────────────────────────────
# Step 4 – aggregate by (mercancia, partida arancelaria)
# ─────────────────────────────────────────────────────────────────────────────

def aggregate(lineas: list) -> list:
    """
    Group lines by (mercancia, partida_arancel) and sum numeric fields.
    """
    seen = OrderedDict()

    for l in lineas:
        key = (l['mercancia'], l['partida_arancel'])
        if key not in seen:
            seen[key] = {
                'mercancia': l['mercancia'],
                'partida':   l['partida_arancel'],
                'bx':        0.0,
                'valor':     0.0,
                'bruto':     0.0,
                'neto':      0.0,
                'm2':        0.0,
            }
        g = seen[key]
        g['bx']    += l['bultos']
        g['bruto'] += l['bruto']
        g['neto']  += l['neto']
        g['m2']    += l['m2']
        if l['valor'] is not None:
            g['valor'] += l['valor']

    result = []
    for g in seen.values():
        g['bx']    = int(round(g['bx']))
        g['bruto'] = round(g['bruto'], 2)
        g['neto']  = round(g['neto'],  2)
        g['m2']    = round(g['m2'],    2)
        g['valor'] = round(g['valor'], 2)
        result.append(g)

    log.info("Aggregated into %d MERCANCIA/PARTIDA rows.", len(result))
    return result


# ─────────────────────────────────────────────────────────────────────────────
# Step 4 – write output ODS
# ─────────────────────────────────────────────────────────────────────────────

def _make_cell(doc, value: str, bold: bool = False, bg: str = None) -> TableCell:
    style_name = None
    if bold or bg:
        style = Style(name=f"ce_{id(value)}_{bold}_{bg}", family="table-cell")
        if bold:
            style.addElement(TextProperties(fontweight="bold"))
        if bg:
            style.addElement(TableCellProperties(backgroundcolor=bg))
        doc.automaticstyles.addElement(style)
        style_name = style.getAttribute("name")

    cell = TableCell()
    if style_name:
        cell.setAttribute("stylename", style_name)

    p = P(text=value)
    if bold:
        ts = Style(name=f"ts_{id(value)}", family="text")
        ts.addElement(TextProperties(fontweight="bold"))
        doc.automaticstyles.addElement(ts)
        p.setAttribute("stylename", ts.getAttribute("name"))
    cell.addElement(p)
    return cell


def _row_from_values(doc, values: list, bold=False, bg=None) -> TableRow:
    row = TableRow()
    for v in values:
        row.addElement(_make_cell(doc, str(v) if v is not None else "", bold=bold, bg=bg))
    return row


def _fill_summary_sheet(doc, sheet, summary: list) -> None:
    HEADER_BG = "#C0C0C0"
    headers = [
        "MERCANCIA", "PARTIDA",
        "Suma - BX", "Suma - VALOR",
        "Suma - BRUTO", "Suma - NETO", "Suma - M22",
    ]
    sheet.addElement(_row_from_values(doc, headers, bold=True, bg=HEADER_BG))

    for r in summary:
        row_vals = [
            r["mercancia"],
            r["partida"],
            str(r["bx"])     if r["bx"]    else "",
            _fmt(r["valor"]) if r["valor"] else "",
            _fmt(r["bruto"]) if r["bruto"] else "",
            _fmt(r["neto"])  if r["neto"]  else "",
            _fmt(r["m2"])    if r["m2"]    else "",
        ]
        sheet.addElement(_row_from_values(doc, row_vals))


def inject_sheet_into_ods(summary: list, source_ods: str, output_path: str) -> None:
    """
    Copy source_ods to output_path and inject 'Resumen_Partidas' as a new sheet.
    Existing sheets are preserved. Idempotent: replaces sheet if already present.
    """
    shutil.copy2(source_ods, output_path)
    doc = load(output_path)

    for existing in doc.spreadsheet.getElementsByType(Table):
        if existing.getAttribute("name") == "Resumen_Partidas":
            doc.spreadsheet.removeChild(existing)
            log.info("Replaced existing 'Resumen_Partidas' sheet.")
            break

    sheet = Table(name="Resumen_Partidas")
    doc.spreadsheet.addElement(sheet)
    _fill_summary_sheet(doc, sheet, summary)
    doc.save(output_path)
    log.info("Injected 'Resumen_Partidas' into %s", output_path)


def write_output(summary: list, output_path: str) -> None:
    """Write a standalone ODS with only the Resumen_Partidas sheet."""
    doc   = OpenDocumentSpreadsheet()
    sheet = Table(name="Resumen_Partidas")
    doc.spreadsheet.addElement(sheet)
    _fill_summary_sheet(doc, sheet, summary)
    doc.save(output_path)
    log.info("Standalone output written to %s", output_path)


# ─────────────────────────────────────────────────────────────────────────────
# Public API  (called by processor.py / tool_registry.py)
# ─────────────────────────────────────────────────────────────────────────────

def process(
    ods_path: str,
    output_path: str,
    factura_path: Optional[str] = None,
    mapping_path: Optional[str] = None,
    inject: bool = True,
) -> list:
    """
    Full pipeline: ODS + FACTURA + mapping → Resumen_Partidas ODS.

    Parameters
    ----------
    ods_path     : path to the input ODS (Hoja1 + Hoja1_2)
    output_path  : where to write the result ODS
    factura_path : path to FACTURA XLSX (optional but recommended)
    mapping_path : path to product_mapping.csv (default: next to this script)
    inject       : True  -> copy source ODS and add Resumen_Partidas sheet
                   False -> write standalone ODS with only the summary
    """
    if not os.path.exists(ods_path):
        raise FileNotFoundError(f"ODS not found: {ods_path}")
    if factura_path and not os.path.exists(factura_path):
        raise FileNotFoundError(f"FACTURA not found: {factura_path}")

    csv_path = mapping_path or str(MAPPING_FILE)
    if not os.path.exists(csv_path):
        raise FileNotFoundError(
            f"product_mapping.csv not found: {csv_path}\n"
            f"Place it next to extract_croton.py or pass --mapping <path>"
        )

    lineas  = read_hoja1_2(ods_path)
    rules   = load_mapping(csv_path)

    # Format B lines already have mercancia + partida_arancel populated — skip mapping
    fmt_b_lines = [l for l in lineas if 'mercancia' in l]
    fmt_a_lines = [l for l in lineas if 'mercancia' not in l]

    if fmt_b_lines:
        log.info("Format B: %d lines already have MERCANCIA/PARTIDA — skipping mapping.", len(fmt_b_lines))
    if fmt_a_lines:
        fmt_a_lines = apply_mapping(fmt_a_lines, rules)

    lineas = fmt_b_lines + fmt_a_lines

    if factura_path:
        factura = load_factura(factura_path)
        lineas  = enrich_valor_from_factura(lineas, factura)
    else:
        log.info("No FACTURA provided — VALOR taken from ODS only.")
        for l in lineas:
            if l['valor'] is None:
                l['valor'] = 0.0

    summary = aggregate(lineas)

    if inject:
        inject_sheet_into_ods(summary, ods_path, output_path)
    else:
        write_output(summary, output_path)

    total_bx    = sum(r["bx"]    for r in summary)
    total_valor = sum(r["valor"] for r in summary)
    total_bruto = sum(r["bruto"] for r in summary)
    total_neto  = sum(r["neto"]  for r in summary)
    total_m2    = sum(r["m2"]    for r in summary)

    log.info(
        "Done — %d partidas | BX=%d VALOR=%.2f EUR BRUTO=%.2f NETO=%.2f M2=%.2f",
        len(summary), total_bx, total_valor, total_bruto, total_neto, total_m2,
    )
    return summary


# ─────────────────────────────────────────────────────────────────────────────
# CLI  (for batch / server use)
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Croton ODS (Hoja1_2) + FACTURA XLSX -> Resumen_Partidas ODS"
    )
    parser.add_argument("input_ods", help="Input ODS (with Hoja1 + Hoja1_2)")
    parser.add_argument("-o", "--output", dest="output_ods", required=True,
                        help="Output ODS path")
    parser.add_argument("--factura", default=None,
                        help="FACTURA XLSX path (optional but recommended)")
    parser.add_argument("--mapping", default=None,
                        help="product_mapping.csv path (default: next to this script)")
    parser.add_argument("--no-inject", action="store_true", default=False,
                        help="Write standalone ODS instead of injecting into source")
    # Legacy flag kept for backward compatibility with existing processor.py calls
    parser.add_argument("--inject", action="store_true", default=False,
                        help="(legacy, now default) Inject sheet into source ODS")
    args = parser.parse_args()

    if os.path.isdir(args.output_ods):
        parser.error(f"Output '{args.output_ods}' is a directory — pass a file path.")

    summary = process(
        ods_path     = args.input_ods,
        output_path  = args.output_ods,
        factura_path = args.factura,
        mapping_path = args.mapping,
        inject       = not args.no_inject,
    )

    total_valor = sum(r["valor"] for r in summary)
    total_bruto = sum(r["bruto"] for r in summary)
    total_neto  = sum(r["neto"]  for r in summary)
    total_m2    = sum(r["m2"]    for r in summary)
    print(f"Done — {len(summary)} partidas -> {args.output_ods}")
    print(f"VALOR={total_valor:.2f} EUR  BRUTO={total_bruto:.2f}kg  "
          f"NETO={total_neto:.2f}kg  M2={total_m2:.2f}")


if __name__ == "__main__":
    main()
