#!/usr/bin/env python3
"""
Croton Packing List Processor  (v2 — Hoja1_2 format)
======================================================
Input : ODS packing-list  — two sheets:
          * Hoja1    = raw packing list (CODIGO interno)
          * Hoja1_2  = enriched sheet generated by operators (PARTIDA / referencia)
                       ← THIS is the sheet we read
        FACTURA XLSX  — invoice with commercial values per REFERENCIA

Output: ODS with an extra 'Resumen_Partidas' sheet (injected into source ODS)
        or standalone ODS (write_output mode).

Why no product_mapping needed:
  Hoja1_2 col3 already contains the REFERENCIA/PARTIDA that operators assigned.
  That same REFERENCIA is col0 in the FACTURA → direct join, no CSV mapping.

Pipeline:
  Hoja1_2  →  extract summary rows (one per product group)
           →  enrich VALOR proportionally from FACTURA XLSX
           →  aggregate by (MERCANCIA, PARTIDA)  →  Resumen_Partidas ODS sheet

Hoja1_2 column layout (0-based):
  0  = LINEA
  1  = Nº BULTO
  2  = DESCRIPCION   <- MERCANCIA
  3  = PARTIDA       <- REFERENCIA / codigo arancelario
  4  = NºPALET
  5  = PESO NETO kg/bulto
  6  = PESO BRUTO kg/bulto
  7  = CANT. del bulto
  8  = CANT. TOTAL MT/UD  <- non-empty -> summary row for the group
  9  = m2 total del grupo
  10 = gramos (gramaje)
  11 = neto total del grupo (kg)
  12 = bruto total del grupo (kg)
  13 = bultos (nº bultos del grupo)
  14 = valor € (may be empty -> computed from FACTURA)

Summary rows are identified by col8 having a numeric value
(not empty and not "#¡DIV/0!").  Individual bulto rows are ignored.
"""

import os
import sys
import shutil
import logging
import argparse
import zipfile
from collections import OrderedDict, defaultdict
from pathlib import Path
from xml.etree import ElementTree as ET
from typing import Optional

import openpyxl
from odf.opendocument import load, OpenDocumentSpreadsheet
from odf.table import Table, TableRow, TableCell
from odf.text import P
from odf.style import Style, TextProperties, TableCellProperties

# ─────────────────────────────────────────────────────────────────────────────
# Logging
# ─────────────────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers – parse numbers
# ─────────────────────────────────────────────────────────────────────────────

def _parse_num(value: str) -> Optional[float]:
    """Parse Spanish-formatted number string to float. Returns None if not a number."""
    if not value or value.strip() in ('#\xa1DIV/0!', '#DIV/0!', '#N/A', '#REF!', ''):
        return None
    clean = value.strip().replace('\xa0', '').replace('.', '').replace(',', '.')
    try:
        return float(clean)
    except ValueError:
        return None


def _fmt(value: float) -> str:
    """Format float to Spanish-style string (comma decimal, no trailing zeros)."""
    if value == 0:
        return ""
    s = f"{value:.4f}".rstrip("0").rstrip(".")
    return s.replace(".", ",")


# ─────────────────────────────────────────────────────────────────────────────
# Step 1 – read Hoja1_2 from ODS
# ─────────────────────────────────────────────────────────────────────────────

def _ods_sheet_names(path: str) -> list:
    """Return all sheet names in the ODS file."""
    with zipfile.ZipFile(path) as z:
        with z.open('content.xml') as f:
            tree = ET.parse(f)
    ns = {'table': 'urn:oasis:names:tc:opendocument:xmlns:table:1.0'}
    return [
        s.get('{urn:oasis:names:tc:opendocument:xmlns:table:1.0}name')
        for s in tree.getroot().findall('.//table:table', ns)
    ]


def _read_ods_sheet(path: str, sheet_name: str) -> list:
    """Read one ODS sheet into a list of row-lists (all values as strings)."""
    with zipfile.ZipFile(path) as z:
        with z.open('content.xml') as f:
            tree = ET.parse(f)
    root = tree.getroot()
    ns = {
        'table': 'urn:oasis:names:tc:opendocument:xmlns:table:1.0',
        'text':  'urn:oasis:names:tc:opendocument:xmlns:text:1.0',
    }
    for sheet in root.findall('.//table:table', ns):
        name = sheet.get('{urn:oasis:names:tc:opendocument:xmlns:table:1.0}name')
        if name != sheet_name:
            continue
        rows_out = []
        for row in sheet.findall('table:table-row', ns):
            vals = []
            for cell in row.findall('table:table-cell', ns):
                rep = cell.get(
                    '{urn:oasis:names:tc:opendocument:xmlns:table:1.0}'
                    'number-columns-repeated'
                )
                txt = ''.join(p.text or '' for p in cell.findall('.//text:p', ns))
                n = int(rep) if rep and int(rep) < 50 else 1
                vals.extend([txt] * n)
            rows_out.append(vals)
        return rows_out
    raise ValueError(f"Sheet '{sheet_name}' not found in {path}")


def _detect_enriched_sheet(path: str) -> str:
    """
    Auto-detect the enriched sheet (Hoja1_2 or equivalent).
    Priority:
      1. Any sheet whose name contains '1_2' or '1.2'
      2. Second sheet (index 1)
      3. First (and only) sheet
    """
    names = _ods_sheet_names(path)
    for n in names:
        if '1_2' in n or '1.2' in n:
            log.info("Using enriched sheet '%s' from %s.", n, path)
            return n
    if len(names) > 1:
        log.info("No '*1_2*' sheet found; using second sheet '%s'.", names[1])
        return names[1]
    log.warning("Only one sheet found; using '%s'.", names[0])
    return names[0]


def read_hoja1_2(ods_path: str) -> list:
    """
    Read Hoja1_2 (or equivalent enriched sheet) and return one dict per
    product-group summary row.

    A row is a 'summary row' when col8 (CANT.TOTAL MT/UD) contains a
    numeric value.  Individual bulto rows (col8 empty or error) are skipped.

    Returns list of dicts:
      referencia, descripcion, cant_total, m2, neto, bruto, bultos, valor
    """
    sheet_name = _detect_enriched_sheet(ods_path)
    rows = _read_ods_sheet(ods_path, sheet_name)

    result = []
    for row in rows[1:]:   # skip header (row 0)
        while len(row) < 15:
            row.append('')

        cant_total = _parse_num(row[8])
        if cant_total is None:
            continue   # individual bulto row -> skip

        referencia  = row[3].strip()
        descripcion = row[2].strip()
        if not referencia or not descripcion:
            continue

        result.append({
            'referencia':  referencia,
            'descripcion': descripcion,
            'cant_total':  cant_total,
            'm2':          _parse_num(row[9])  or 0.0,
            'neto':        _parse_num(row[11]) or 0.0,
            'bruto':       _parse_num(row[12]) or 0.0,
            'bultos':      _parse_num(row[13]) or 0.0,
            'valor':       _parse_num(row[14]),   # None if empty
        })

    log.info("Read %d summary rows from sheet '%s'.", len(result), sheet_name)
    return result


# ─────────────────────────────────────────────────────────────────────────────
# Step 2 – load FACTURA XLSX and enrich VALOR
# ─────────────────────────────────────────────────────────────────────────────

def load_factura(xlsx_path: str) -> dict:
    """
    Load FACTURA XLSX and return per-REFERENCIA invoice data:
      REFERENCIA_UPPER -> { cant_total, importe_total }

    Column layout (sheet 'TOTAL FRA.' or first sheet):
      col A (0) = REFERENCIA
      col F (5) = CANTIDAD MTS / KGS
      col I (8) = IMPORTE EUR

    Multiple lines with the same REFERENCIA are summed (e.g. RF385 BLANCA +
    RF385 COLORES -> single entry).
    """
    wb = openpyxl.load_workbook(xlsx_path, data_only=True)
    ws = wb["TOTAL FRA."] if "TOTAL FRA." in wb.sheetnames else wb.active
    log.info("Reading FACTURA from sheet '%s' in %s.", ws.title, xlsx_path)

    _SKIP = {
        'referencia', 'importe', 'forma', 'total', 'transferencia',
        'domicilio', 'incoterm', 'ifortex', 'mendez', 'nif', 'lot',
        'tanger', 'marruecos', 'avda', 'tel', 'num.', 'num',
    }

    cant_map    = defaultdict(float)
    importe_map = defaultdict(float)

    for row in ws.iter_rows(values_only=True):
        ref_raw = row[0]
        if ref_raw is None:
            continue
        ref = str(ref_raw).strip()
        if not ref or ref.lower().split()[0] in _SKIP:
            continue
        try:
            cant    = float(row[5]) if row[5] is not None else None
            importe = float(row[8]) if row[8] is not None else None
        except (ValueError, TypeError):
            continue
        if cant is None or importe is None or importe < 1.0:
            continue
        cant_map[ref.upper()]    += cant
        importe_map[ref.upper()] += round(importe, 4)

    wb.close()

    result = {
        ref: {'cant_total': cant_map[ref], 'importe_total': importe_map[ref]}
        for ref in importe_map
    }
    log.info(
        "Loaded FACTURA: %d references, total %.2f EUR.",
        len(result), sum(v['importe_total'] for v in result.values())
    )
    return result


def enrich_valor_from_factura(lineas: list, factura: dict) -> list:
    """
    Fill in missing VALOR for each line using the FACTURA (proportional).

      valor_linea = (cant_linea / cant_total_factura_ref) * importe_factura_ref

    ODS valor takes priority: if valor is already set (not None) -> keep it.
    """
    for linea in lineas:
        if linea['valor'] is not None:
            linea['valor_fuente'] = 'ODS'
            continue

        ref = linea['referencia'].upper()
        if ref in factura:
            inv = factura[ref]
            if inv['cant_total'] and inv['cant_total'] > 0:
                proporcion = linea['cant_total'] / inv['cant_total']
                linea['valor'] = round(proporcion * inv['importe_total'], 2)
                linea['valor_fuente'] = 'FACTURA'
            else:
                linea['valor_fuente'] = 'SIN_DATOS'
        else:
            linea['valor_fuente'] = 'SIN_REF'
            log.warning(
                "REFERENCIA '%s' (%s) not found in FACTURA — VALOR left empty.",
                linea['referencia'], linea['descripcion'][:40]
            )

    return lineas


# ─────────────────────────────────────────────────────────────────────────────
# Step 3 – aggregate by (descripcion, referencia)
# ─────────────────────────────────────────────────────────────────────────────

def aggregate(lineas: list) -> list:
    """
    Group lines by (descripcion, referencia) and sum numeric fields.
    In the new format each line is already a product summary row, but the
    same (descripcion, referencia) pair could theoretically appear on
    multiple rows — this collapses them cleanly.
    """
    seen = OrderedDict()

    for l in lineas:
        key = (l['descripcion'], l['referencia'])
        if key not in seen:
            seen[key] = {
                'mercancia':    l['descripcion'],
                'partida':      l['referencia'],
                'bx':           0.0,
                'valor':        0.0,
                'bruto':        0.0,
                'neto':         0.0,
                'm2':           0.0,
                'valor_fuente': set(),
            }
        g = seen[key]
        g['bx']    += l['bultos']
        g['bruto'] += l['bruto']
        g['neto']  += l['neto']
        g['m2']    += l['m2']
        if l['valor'] is not None:
            g['valor'] += l['valor']
        g['valor_fuente'].add(l.get('valor_fuente', '?'))

    result = []
    for g in seen.values():
        g['valor_fuente'] = '/'.join(sorted(g['valor_fuente']))
        g['bx']    = int(round(g['bx']))
        g['bruto'] = round(g['bruto'], 2)
        g['neto']  = round(g['neto'],  2)
        g['m2']    = round(g['m2'],    2)
        g['valor'] = round(g['valor'], 2)
        result.append(g)

    log.info("Aggregated into %d MERCANCIA/PARTIDA rows.", len(result))
    return result


# ─────────────────────────────────────────────────────────────────────────────
# Step 4 – write output ODS
# ─────────────────────────────────────────────────────────────────────────────

def _make_cell(doc, value: str, bold: bool = False, bg: str = None) -> TableCell:
    style_name = None
    if bold or bg:
        style = Style(name=f"ce_{id(value)}_{bold}_{bg}", family="table-cell")
        if bold:
            style.addElement(TextProperties(fontweight="bold"))
        if bg:
            style.addElement(TableCellProperties(backgroundcolor=bg))
        doc.automaticstyles.addElement(style)
        style_name = style.getAttribute("name")

    cell = TableCell()
    if style_name:
        cell.setAttribute("stylename", style_name)

    p = P(text=value)
    if bold:
        ts = Style(name=f"ts_{id(value)}", family="text")
        ts.addElement(TextProperties(fontweight="bold"))
        doc.automaticstyles.addElement(ts)
        p.setAttribute("stylename", ts.getAttribute("name"))
    cell.addElement(p)
    return cell


def _row_from_values(doc, values: list, bold=False, bg=None) -> TableRow:
    row = TableRow()
    for v in values:
        row.addElement(_make_cell(doc, str(v) if v is not None else "", bold=bold, bg=bg))
    return row


def _fill_summary_sheet(doc, sheet, summary: list) -> None:
    HEADER_BG = "#C0C0C0"
    headers = [
        "MERCANCIA", "PARTIDA",
        "Suma - BX", "Suma - VALOR",
        "Suma - BRUTO", "Suma - NETO", "Suma - M22",
    ]
    sheet.addElement(_row_from_values(doc, headers, bold=True, bg=HEADER_BG))

    for r in summary:
        row_vals = [
            r["mercancia"],
            r["partida"],
            str(r["bx"])     if r["bx"]    else "",
            _fmt(r["valor"]) if r["valor"] else "",
            _fmt(r["bruto"]) if r["bruto"] else "",
            _fmt(r["neto"])  if r["neto"]  else "",
            _fmt(r["m2"])    if r["m2"]    else "",
        ]
        sheet.addElement(_row_from_values(doc, row_vals))


def inject_sheet_into_ods(summary: list, source_ods: str, output_path: str) -> None:
    """
    Copy source_ods to output_path and inject 'Resumen_Partidas' as a new sheet.
    Existing sheets are preserved. Idempotent: replaces sheet if already present.
    """
    shutil.copy2(source_ods, output_path)
    doc = load(output_path)

    for existing in doc.spreadsheet.getElementsByType(Table):
        if existing.getAttribute("name") == "Resumen_Partidas":
            doc.spreadsheet.removeChild(existing)
            log.info("Replaced existing 'Resumen_Partidas' sheet.")
            break

    sheet = Table(name="Resumen_Partidas")
    doc.spreadsheet.addElement(sheet)
    _fill_summary_sheet(doc, sheet, summary)
    doc.save(output_path)
    log.info("Injected 'Resumen_Partidas' into %s", output_path)


def write_output(summary: list, output_path: str) -> None:
    """Write a standalone ODS with only the Resumen_Partidas sheet."""
    doc   = OpenDocumentSpreadsheet()
    sheet = Table(name="Resumen_Partidas")
    doc.spreadsheet.addElement(sheet)
    _fill_summary_sheet(doc, sheet, summary)
    doc.save(output_path)
    log.info("Standalone output written to %s", output_path)


# ─────────────────────────────────────────────────────────────────────────────
# Public API  (called by processor.py / tool_registry.py)
# ─────────────────────────────────────────────────────────────────────────────

def process(
    ods_path: str,
    output_path: str,
    factura_path: Optional[str] = None,
    inject: bool = True,
) -> list:
    """
    Full pipeline: ODS + optional FACTURA -> Resumen_Partidas ODS.

    Parameters
    ----------
    ods_path     : path to the input ODS (Hoja1 + Hoja1_2)
    output_path  : where to write the result ODS
    factura_path : path to FACTURA XLSX (optional but recommended)
    inject       : True  -> copy source ODS and add Resumen_Partidas sheet
                   False -> write standalone ODS with only the summary

    Returns the summary list[dict] for further use if needed.
    """
    if not os.path.exists(ods_path):
        raise FileNotFoundError(f"ODS not found: {ods_path}")
    if factura_path and not os.path.exists(factura_path):
        raise FileNotFoundError(f"FACTURA not found: {factura_path}")

    lineas = read_hoja1_2(ods_path)

    if factura_path:
        factura = load_factura(factura_path)
        lineas  = enrich_valor_from_factura(lineas, factura)
    else:
        log.info("No FACTURA provided — VALOR taken from ODS only.")
        for l in lineas:
            if l['valor'] is None:
                l['valor_fuente'] = 'SIN_FACTURA'

    summary = aggregate(lineas)

    if inject:
        inject_sheet_into_ods(summary, ods_path, output_path)
    else:
        write_output(summary, output_path)

    total_bx    = sum(r["bx"]    for r in summary)
    total_valor = sum(r["valor"] for r in summary)
    total_bruto = sum(r["bruto"] for r in summary)
    total_neto  = sum(r["neto"]  for r in summary)
    total_m2    = sum(r["m2"]    for r in summary)

    log.info(
        "Done — %d partidas | BX=%d VALOR=%.2f EUR BRUTO=%.2f NETO=%.2f M2=%.2f",
        len(summary), total_bx, total_valor, total_bruto, total_neto, total_m2,
    )
    return summary


# ─────────────────────────────────────────────────────────────────────────────
# CLI  (for batch / server use)
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Croton ODS (Hoja1_2) + FACTURA XLSX -> Resumen_Partidas ODS"
    )
    parser.add_argument("input_ods", help="Input ODS (with Hoja1 + Hoja1_2)")
    parser.add_argument("-o", "--output", dest="output_ods", required=True,
                        help="Output ODS path")
    parser.add_argument("--factura", default=None,
                        help="FACTURA XLSX path (optional but recommended)")
    parser.add_argument("--no-inject", action="store_true", default=False,
                        help="Write standalone ODS instead of injecting into source")
    args = parser.parse_args()

    if os.path.isdir(args.output_ods):
        parser.error(f"Output '{args.output_ods}' is a directory — pass a file path.")

    summary = process(
        ods_path     = args.input_ods,
        output_path  = args.output_ods,
        factura_path = args.factura,
        inject       = not args.no_inject,
    )

    total_valor = sum(r["valor"] for r in summary)
    total_bruto = sum(r["bruto"] for r in summary)
    total_neto  = sum(r["neto"]  for r in summary)
    total_m2    = sum(r["m2"]    for r in summary)
    print(f"Done — {len(summary)} partidas -> {args.output_ods}")
    print(f"VALOR={total_valor:.2f} EUR  BRUTO={total_bruto:.2f}kg  "
          f"NETO={total_neto:.2f}kg  M2={total_m2:.2f}")


if __name__ == "__main__":
    main()
