server {
  listen 80;
  client_max_body_size 200m;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }

  location /api/lear_cable/ {
    proxy_pass http://api_lear_cable:8000/api/lear_cable/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
