server {
  listen 80;
  client_max_body_size 1100m;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }

  location /api/lear_cable/ {
    proxy_pass http://api_lear_cable:8000/api/lear_cable/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /api/import_partida/ {
    proxy_pass http://api_import_partida:8000/api/import_partida/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
  # Textual Serve (TUI in browser)
  location /tools/json_form/ {
    proxy_pass http://tui_json_form:8000/;

    proxy_http_version 1.1;
    proxy_set_header Host $host;

    # WebSocket support
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_read_timeout 3600;
    proxy_send_timeout 3600;
  }
}
